name: Test

on: [push, pull_request]

jobs:

  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Run Flake8
        run: |
          python -m pip install flake8
          flake8

  unittest:
    name: Unittest
    timeout-minutes: 15
    strategy:
      matrix:
        python: [3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip freeze
      - name: Run tests using pytest
        run: ./scripts/pytest
